### ISSUE TITLE
bs_search throws an error in R 3.4.0

### ISSUE THREAD

**Issue by pkraker** [ropenscilabs/rbace#12]
`bs_search` throws the following error in R 3.4.0. Downgrading crul to 0.3.0 solved the problem.

```
Error: 'Access denied for IP address XXX.XXX.XXX.XX and user agent libcurl/7.35.0 r-curl/2.6 crul/0.3.6.
' does not exist in current working directory
```

**Comment by sckott** [comment]
thanks will have a look

**Comment by sckott** [comment]
I have a feeling it may be that BASE is whitelisting IP address + EXACT user agent string

and b/c we include version numbers for the pkgs in the user agent string, the user agent string is now different with a different `crul` version 

further evidence to support this is that other R clients that use `crul` are all working fine 

does that sound right @pietsch ?

**Comment by sckott** [comment]
@pietsch would it be possible to regex (or however you're checking) to just the pkg names in the UA string?  i could change it to only give the pkg names in the UA string, without the versions - then it won't change when the versions of those pkgs change

**Comment by pietsch** [comment]
For authentication to succeed, the IP address or the UA has to match. Please e-mail me a range of UA strings (or a regex) you would like to be allowed.

**Comment by sckott** [comment]
sent an email

**Comment by sckott** [comment]
@pkraker try again after reinstalling - should be good to go now

**Comment by pkraker** [comment]
@sckott yes, confirmed both on my local machine and the server.
