### ISSUE TITLE
Move figures to ./man/figures

### ISSUE THREAD

**Issue by jeroen** [ropenscilabs/rbace#13]
See https://docs.ropensci.org/rbace/ and this comment from Hadley: https://github.com/ropensci/rotemplate/issues/19#issuecomment-506315565

You can also have a look where other packages store `readme.md` figures:

 - https://github.com/ropensci/tidyhydat/
 - https://github.com/ropensci/drake/

**Comment by sckott** [comment]
done in c03401998818d5b18cee6e74e35428aa41a6032f
