### ISSUE TITLE
Parameter 'func' not found! error

### ISSUE THREAD

**Issue by jesstytam** [ropenscilabs/rbace#18]
I've been trying to use the API for queries using both `httr::POST()` and `httr::GET()`.

```r
test <- httr::POST(url = "https://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi", body = "dctitle:Macropus rufus") 
test
#> Response [https://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi]
#>   Date: 2021-05-06 01:48
#>   Status: 200
#>   Content-Type: text/xml; charset=UTF-8
#>   Size: 82 B
#> <?xml version="1.0" encoding="utf-8"?>
test<- httr::GET("https://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi",
                   query = list(query = "dctitle:Macropus rufus"),
                   httpAccept = "application/xml")
test
#> Response [https://api.base-search.net/cgi-bin/BaseHttpSearchInterface.fcgi?query=dctitle%3AMacropus%20rufus]
#>   Date: 2021-05-06 01:58
#>   Status: 200
#>   Content-Type: text/xml; charset=UTF-8
#>   Size: 82 B
#> <?xml version="1.0" encoding="utf-8"?>
```

While both of them returned data successfully (html status 200), I am having the same issues extracting data from both `POST()` and `GET()` outputs because of the error `Parameter 'func' not found!`. 

```r
httr::content(test, as = "text")
#> [1] "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\n<error>Parameter 'func' not found!</error>"
XML::xmlParse(test)
#> <?xml version="1.0" encoding="utf-8"?>
#> <error>Parameter 'func' not found!</error>
```

Is this potentially a problem with the API or just my code? I've used the same code for other APIs and have never encountered this error before. Any help would be greatly appreciated. Thanks!

Here is my sessions info:

─ Session info ─────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Ubuntu 16.04.7 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_AU:en                    
 collate  en_AU.UTF-8                 
 ctype    en_AU.UTF-8                 
 tz       Australia/Sydney            
 date     2021-05-06                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────
 ! package     * version    date       lib source                           
   abind         1.4-5      2016-07-21 [1] CRAN (R 4.0.2)                   
   ape           5.5        2021-04-25 [1] CRAN (R 4.0.2)                   
   assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.2)                   
   backports     1.2.1      2020-12-09 [1] CRAN (R 4.0.2)                   
   bold          1.1.0      2020-06-17 [1] CRAN (R 4.0.2)                   
   broom         0.7.6      2021-04-05 [1] CRAN (R 4.0.2)                   
   cachem        1.0.4      2021-02-13 [1] CRAN (R 4.0.2)                   
   callr         3.7.0      2021-04-20 [1] CRAN (R 4.0.2)                   
   car           3.0-10     2020-09-29 [1] CRAN (R 4.0.2)                   
   carData       3.0-4      2020-05-22 [1] CRAN (R 4.0.2)                   
   cellranger    1.1.0      2016-07-27 [1] CRAN (R 4.0.2)                   
   cli           2.5.0      2021-04-26 [1] CRAN (R 4.0.2)                   
   codetools     0.2-18     2020-11-04 [1] CRAN (R 4.0.2)                   
   colorspace    2.0-1      2021-05-04 [1] CRAN (R 4.0.2)                   
   conditionz    0.1.0      2019-04-24 [1] CRAN (R 4.0.2)                   
   crayon        1.4.1      2021-02-08 [1] CRAN (R 4.0.2)                   
   crul          1.1.0      2021-02-15 [1] CRAN (R 4.0.2)                   
   curl          4.3.1      2021-04-30 [1] CRAN (R 4.0.2)                   
   data.table  * 1.14.0     2021-02-21 [1] CRAN (R 4.0.2)                   
   DBI           1.1.1      2021-01-15 [1] CRAN (R 4.0.2)                   
   dbplyr        2.1.1      2021-04-06 [1] CRAN (R 4.0.2)                   
   desc          1.3.0      2021-03-05 [1] CRAN (R 4.0.2)                   
   devtools      2.4.1      2021-05-05 [1] CRAN (R 4.0.2)                   
   digest        0.6.27     2020-10-24 [1] CRAN (R 4.0.2)                   
   dplyr       * 1.0.6      2021-05-05 [1] CRAN (R 4.0.2)                   
   ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.0.2)                   
   evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.2)                   
   fansi         0.4.2      2021-01-15 [1] CRAN (R 4.0.2)                   
   fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.0.2)                   
   forcats     * 0.5.1      2021-01-27 [1] CRAN (R 4.0.2)                   
   foreach       1.5.1      2020-10-15 [1] CRAN (R 4.0.2)                   
   foreign       0.8-81     2020-12-22 [1] CRAN (R 4.0.2)                   
   fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                   
   generics      0.1.0      2020-10-31 [1] CRAN (R 4.0.2)                   
   ggplot2     * 3.3.3      2020-12-30 [1] CRAN (R 4.0.2)                   
   ggpubr      * 0.4.0      2020-06-27 [1] CRAN (R 4.0.2)                   
   ggsignif      0.6.1      2021-02-23 [1] CRAN (R 4.0.2)                   
   glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                   
   gtable        0.3.0      2019-03-25 [1] CRAN (R 4.0.2)                   
   gtools      * 3.8.2      2020-03-31 [1] CRAN (R 4.0.2)                   
   haven         2.4.1      2021-04-23 [1] CRAN (R 4.0.2)                   
   hms           1.0.0      2021-01-13 [1] CRAN (R 4.0.2)                   
   htmltools     0.5.1.1    2021-01-22 [1] CRAN (R 4.0.2)                   
   httpcode      0.3.0      2020-04-10 [1] CRAN (R 4.0.2)                   
   httr        * 1.4.2      2020-07-20 [1] CRAN (R 4.0.2)                   
   iterators     1.0.13     2020-10-15 [1] CRAN (R 4.0.2)                   
   jsonlite    * 1.7.2      2020-12-09 [1] CRAN (R 4.0.2)                   
   knitr         1.33       2021-04-24 [1] CRAN (R 4.0.2)                   
   lattice       0.20-41    2020-04-02 [4] CRAN (R 4.0.0)                   
   lens2r      * 0.0.0.9000 2021-03-08 [1] Github (sbalci/lens2r@ec115b4)   
   lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.0.2)                   
   lubridate     1.7.10     2021-02-26 [1] CRAN (R 4.0.2)                   
   magrittr    * 2.0.1      2020-11-17 [1] CRAN (R 4.0.2)                   
   memoise       2.0.0      2021-01-26 [1] CRAN (R 4.0.2)                   
   modelr        0.1.8      2020-05-19 [1] CRAN (R 4.0.2)                   
   munsell       0.5.0      2018-06-12 [1] CRAN (R 4.0.2)                   
   nlme          3.1-152    2021-02-04 [1] CRAN (R 4.0.2)                   
   openxlsx      4.2.3      2020-10-27 [1] CRAN (R 4.0.2)                   
   pacman        0.5.1      2019-03-11 [1] CRAN (R 4.0.2)                   
   pillar        1.6.0      2021-04-13 [1] CRAN (R 4.0.2)                   
   pkgbuild      1.2.0      2020-12-15 [1] CRAN (R 4.0.2)                   
   pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.2)                   
   pkgload       1.2.1      2021-04-06 [1] CRAN (R 4.0.2)                   
   plyr          1.8.6      2020-03-03 [1] CRAN (R 4.0.2)                   
   prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.2)                   
   processx      3.5.2      2021-04-30 [1] CRAN (R 4.0.2)                   
   ps            1.6.0      2021-02-28 [1] CRAN (R 4.0.2)                   
   purrr       * 0.3.4      2020-04-17 [1] CRAN (R 4.0.2)                   
   R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                   
   rbace       * 0.2.2      2020-10-13 [1] CRAN (R 4.0.2)                   
   Rcpp          1.0.6      2021-01-15 [1] CRAN (R 4.0.2)                   
   readr       * 1.4.0      2020-10-05 [1] CRAN (R 4.0.2)                   
   readxl        1.3.1      2019-03-13 [1] CRAN (R 4.0.2)                   
   remotes       2.3.0      2021-04-01 [1] CRAN (R 4.0.2)                   
 V reprex        2.0.0      2021-05-06 [1] Github (tidyverse/reprex@d6b12e4)
   reshape       0.8.8      2018-10-23 [1] CRAN (R 4.0.2)                   
   rio           0.5.26     2021-03-01 [1] CRAN (R 4.0.2)                   
   rlang         0.4.11     2021-04-30 [1] CRAN (R 4.0.2)                   
   rmarkdown     2.7        2021-02-19 [1] CRAN (R 4.0.2)                   
   rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.0.2)                   
   rscopus     * 0.6.6      2019-09-17 [1] CRAN (R 4.0.2)                   
   rstatix       0.7.0      2021-02-13 [1] CRAN (R 4.0.2)                   
   rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.0.2)                   
   rvest         1.0.0      2021-03-09 [1] CRAN (R 4.0.2)                   
   scales        1.1.1      2020-05-11 [1] CRAN (R 4.0.2)                   
   sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.2)                   
   stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                   
   stringr     * 1.4.0      2019-02-10 [1] CRAN (R 4.0.2)                   
   taxize      * 0.9.99     2020-10-30 [1] CRAN (R 4.0.2)                   
   testthat      3.0.2      2021-02-14 [1] CRAN (R 4.0.2)                   
   tibble      * 3.1.1      2021-04-18 [1] CRAN (R 4.0.2)                   
   tidyr       * 1.1.3      2021-03-03 [1] CRAN (R 4.0.2)                   
   tidyselect    1.1.1      2021-04-30 [1] CRAN (R 4.0.2)                   
   tidyverse   * 1.3.1      2021-04-15 [1] CRAN (R 4.0.2)                   
   usethis       2.0.1      2021-02-10 [1] CRAN (R 4.0.2)                   
   utf8          1.2.1      2021-03-12 [1] CRAN (R 4.0.2)                   
   uuid          0.1-4      2020-02-26 [1] CRAN (R 4.0.2)                   
   vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.0.2)                   
   withr         2.4.2      2021-04-18 [1] CRAN (R 4.0.2)                   
   wosr        * 0.3.0      2018-11-02 [1] CRAN (R 4.0.2)                   
   xfun          0.22       2021-03-11 [1] CRAN (R 4.0.2)                   
   XML         * 3.99-0.6   2021-03-16 [1] CRAN (R 4.0.2)                   
   xml2          1.3.2      2020-04-23 [1] CRAN (R 4.0.2)                   
   yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.2)                   
   zip           2.1.1      2020-08-27 [1] CRAN (R 4.0.2)                   
   zoo           1.8-9      2021-03-09 [1] CRAN (R 4.0.2)                   

[1] /home/jessicatam/R/x86_64-pc-linux-gnu-library/4.0
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library

 V ── Loaded and on-disk version mismatch.

**Comment by sckott** [comment]
Hi, thanks for opening an issue here. 

First, why don't you just use the functions in this package?  No worries either way, just curious. 

Second, you need to supply a query parameter `func` to the BASE API - see e.g., https://github.com/ropensci/rbace/blob/master/R/bs_search.R#L78 - that's the error message you are getting, its not from R, its from the BASE API server

**Comment by jesstytam** [comment]
Thanks for the help, it is working now!
I'd like to get the number of records found from the query, which seems to be easier this way.

**Comment by sckott** [comment]
glad it works for you
